LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE:= mod
LOCAL_SRC_FILES := ../mod_linux.cc
LOCAL_C_INCLUDES := 
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
LOCAL_SHARED_LIBRARIES =
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= exe_arm
LOCAL_SRC_FILES := ../main.cc 
LOCAL_C_INCLUDES := 
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
LOCAL_SHARED_LIBRARIES = 
include $(BUILD_EXECUTABLE)

